[workspace]
members = [
    "walkers",
    "demo",
    "demo_native",
    "demo_web",
    "demo_android/rust",
    "hypermocker",
]
resolver = "2"

[workspace.package]
version = "0.33.0"

[workspace.dependencies]
image = { version = "0.25", default-features = false }
log = "0.4"
egui = "0.30.0"
egui_extras = { version = "0.30.0", features = ["svg"] }
eframe = "0.30.0"
egui-winit = "0.30.0"
