[package]
name = "walkers"
version = "0.7.0"
repository = "https://github.com/podusowski/walkers"
description = "slippy map widget for egui"
keywords = ["gis", "geography", "gui"]
categories = ["gui", "science::geo"]
authors = ["Piotr Podusowski <podusowski@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
thiserror = "1"
log = "0.4"
egui = "0.22"
egui_extras = { version = "0.22", features = ["image"] }
image = { version = "0.24", features = ["jpeg", "png"] }
geo-types = { version = "0.7" }
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
] }
tokio = { version = "1.28", features = ["macros"] }
#ehttp = "0.3.0"
ehttp = { path = "../ehttp/ehttp" }

#[patch.crates-io]

[dev-dependencies]
eframe = "0.22"
env_logger = "0.10"
approx = "0.5"
mockito = "1.1"
