[workspace]
members = ["walkers", "demo", "demo_native", "demo_web", "demo_android/rust"]
resolver = "2"

[workspace.package]
version = "0.17.0"

[workspace.dependencies]
image = "0.24"
log = "0.4"
egui = "0.25"
egui_extras = { version = "0.25", features = ["svg"] }
eframe = "0.25"
egui-winit = "0.25"
