[package]
name = "walkers"
version.workspace = true
repository = "https://github.com/podusowski/walkers"
description = "slippy map widget for egui"
keywords = ["gis", "geography", "gui"]
categories = ["gui", "science::geo"]
authors = ["Piotr Podusowski <podusowski@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
log.workspace = true
egui.workspace = true
egui_extras.workspace = true
lru = "0.16"
thiserror = "2"
image = { version = "0.25", default-features = false, features = [
    "jpeg",
    "png",
] }
geo-types = { version = "0.7" }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
] }
futures = "0.3.28"
serde = { version = "1", features = ["derive"], optional = true }
reqwest-middleware = "0.4.2"
pmtiles = { version = "0.16.0", default-features = false, features = [
    "mmap-async-tokio",
] }
resvg = "0.45.1"
mvt = "0.10.3"
mvt-reader = "2.1.0"
flate2 = "1.1.2"
tiny-skia = "0.11.4"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen-futures = "0.4"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = "1"
http-cache-reqwest = "0.16.0"

[dev-dependencies]
eframe.workspace = true
env_logger = "0.11"
approx = "0.5"
hypermocker = { path = "../hypermocker" }

[features]
default = []
serde = ["dep:serde", "geo-types/serde", "egui/serde"]
