[package]
name = "walkers"
version.workspace = true
repository = "https://github.com/podusowski/walkers"
description = "slippy map widget for egui"
keywords = ["gis", "geography", "gui"]
categories = ["gui", "science::geo"]
authors = ["Piotr Podusowski <podusowski@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
log.workspace = true
egui.workspace = true
egui_extras.workspace = true
thiserror = "1"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
geo-types = { version = "0.7" }
reqwest = { version = "0.11", default-features = false, features = [
    "rustls-tls",
] }
futures = "0.3.28"
reqwest-middleware = "0.2.4"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen-futures = "0.4.37"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1.28", features = ["macros"] }
http-cache-reqwest = "0.13.0"

[dev-dependencies]
eframe.workspace = true
env_logger = "0.11"
approx = "0.5"
hypermocker = { path = "../hypermocker" }
